CREATE DATABASE SANA;

USE SANA;
CREATE TABLE INFO(
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
FULLNAME VARCHAR (50) NOT NULL,
LASTNAME VARCHAR (50),
EMAILID VARCHAR (250) UNIQUE,
MOBILENO INT (10),
GENDER VARCHAR (250),
DOB DATE DEFAULT current_timestamp,
ADDRESS VARCHAR (250),
CITY VARCHAR (50) DEFAULT "KARACHI", 
PINCODE INT(06),
STATE VARCHAR(50),
COUNTRY VARCHAR(250) DEFAULT "PAKISTAN",
HOBBIES VARCHAR(50) DEFAULT "RECITATION OF QURAN");

SELECT * FROM INFO;

INSERT INTO INFO VALUES(NULL,"SANA", "KIRAN", 03332564, "FEMALE");
